#!/bin/bash
# Baixar arquivos .zip do TSE:
for url in $(cat "fontes_zip.txt")
do
	OUTPUT_FILENAME=$(echo $url | cut -f9 -d'/')
	echo "Baixando arquivo ${OUTPUT_FILENAME}:"
	curl $url \
	-H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.23 (KHTML, like Gecko) Version/10.0 Mobile/14E5239e Safari/602.1' \
	-H "Content-Type: application/json" \
	-o $OUTPUT_FILENAME
done
